spring:
  application:
    name: mortgage-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/yapa
    username: postgres
    password: postgres
    properties:
      schema: yapa

  migrate:
    enabled: true
    resources-paths: db/migration
    baseline-on-migrate: true


jwt:
  secret: ${JWT_SECRET}             # HS256 signing key
  expiration: ${JWT_EXPIRATION:900}     # default 900 seconds (15 min) if not set

app:
  messaging:
    topic: loan.applications
  rateLimit:
    applicantRpm: 60
    officerRpm: 300

kafka:
  bootstrap-servers: localhost:9092
  topics:
    stock.received.v1: stock.received.v1
    stock.reserved.v1: stock.reserved.v1
    stock.released.v1: stock.released.v1
    stock.adjusted.v1: stock.adjusted.v1
    backorder.queued.v1: backorder.queued.v1
    backorder.fulfilled.v1: backorder.fulfilled.v1
  producer:
    client-id: product-service
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
    compression-type: snappy
    enable-idempotence: true
    request-timeout-ms: 30000
    delivery-timeout-ms: 120000
    max-in-flight-requests-per-connection: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: mortgage-service
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.bank.mortgage: INFO