server:
  port: 7001

spring:
  application:
    name: mortgage-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: mortgage
    create-schemas: true
    default-schema: mortgage
    url: jdbc:postgresql://localhost:5433/yapa
    user: postgres
    password: postgres

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/yapa
    username: postgres
    password: postgres
    properties:
      schema: mortgage

jwt:
  secret: "OG1CZD+2pMM10aG8zkC6WPldo5bW/eru/hECqpKRtRM="
  expiration: "900"     # default 900 seconds (15 min) if not set
  refreshExpiration: 2592000        # 30 days
security:
  nationalId:
    hmacKey: "aksCLMXOtFf2BbjwvtNYv4WopyWYPBlCNSD8lWo5A48="
    encKey: "VLZgsnwNxZkAH4qGd/BmIVDGylk7NdBo7nPeokya4EA="
app:
  messaging:
    topic: loan.applications
  rateLimit:
    applicantRpm: 60
    officerRpm: 300

kafka:
  bootstrap-servers: localhost:9092
  topics:
    application.created.v1: loan.applications.v1
    application.status.updated.v1: loan.applications.v1
    document.uploaded.v1: loan.applications.v1
    application.decision.made.v1: loan.applications.v1
    application.withdrawn.v1: loan.applications.v1
    application.deleted.v1: loan.applications.v1
  producer:
    client-id: product-service
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
    compression-type: snappy
    enable-idempotence: true
    request-timeout-ms: 30000
    delivery-timeout-ms: 120000
    max-in-flight-requests-per-connection: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  health:
    jms:
      enabled: false  # Disable JMS health check
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: mortgage-service
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.bank.mortgage: INFO
    org.org.springframework.security: DEBUG
    org.flywaydb: DEBUG  # Added for more detailed Flyway logs