
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Lint (Checkstyle)
        run: mvn -q -f backend/pom.xml -DskipTests checkstyle:check
      - name: Build (skip tests)
        run: mvn -q -f backend/pom.xml -DskipTests clean package
      - name: Build Docker
        run: docker build -t mortgage-service:$(echo $GITHUB_SHA | cut -c1-7) .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: mortgage-service:$(echo $GITHUB_SHA | cut -c1-7)
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'